---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
  labels:
    app: minio


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
  labels:
    app: minio
data:
  MINIO_ROOT_USER: admin
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: "minio-sts-{0...3}.minio-hsvc.minio-ns.svc.cluster.local/data"
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"


---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
  labels:
    app: minio
type: Opaque
data:
  # adminadmin
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==